### ISSUE TITLE
这是什么原因啊？

### ISSUE THREAD

**Issue by MAO-S-K** [coderhukai/yolov5-5.x-annotations#2]
!python /content/drive/MyDrive/yolov5-5.x-annotations-main/train.py --img 640 --batch 16 --epochs 200  --data /content/drive/MyDrive/YOLO/yuanshiyolov5peizhi/yuan.yaml  --cfg /content/drive/MyDrive/yolov5-5.x-annotations-main/models/yolov5s.yaml --weights /content/drive/MyDrive/YOLO/yolov5/yolov5s.pt 

Traceback (most recent call last):
  File "/content/drive/MyDrive/yolov5-5.x-annotations-main/train.py", line 36, in <module>
    import val  # for end-of-epoch mAP
  File "/content/drive/MyDrive/yolov5-5.x-annotations-main/val.py", line 23, in <module>
    from models.experimental import attempt_load
  File "/content/drive/MyDrive/yolov5-5.x-annotations-main/models/experimental.py", line 7, in <module>
    from models.common import Conv, DWConv
  File "/content/drive/MyDrive/yolov5-5.x-annotations-main/models/common.py", line 17, in <module>
    from utils.datasets import letterbox
  File "/content/drive/MyDrive/yolov5-5.x-annotations-main/utils/datasets.py", line 20, in <module>
    matplotlib.use('TkAgg')
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/deprecation.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py", line 1281, in use
    plt.switch_backend(name)
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/pyplot.py", line 237, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

**Comment by PangPangDog** [comment]
调用的是远程服务器调试？
[TkAGG报错](https://blog.csdn.net/qq_36146671/article/details/121467548?spm=1001.2014.3001.5501)

本地的话
matplotlib.use("AGG")试试[](url)

**Comment by HuKai97** [comment]
![image](https://user-images.githubusercontent.com/68494594/143162807-70db312f-3a15-4e16-ad95-3a319969f8cd.png)
